[package]
name = "errors-rs"
version = "0.1.0"
authors = ["the-notable <the-notable@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.26"
